config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/home', to: 'pages#home'

  resources :users
  resources :meals
  resources :menu_items
  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :menu_item 
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :user
	has_many :menu_items
end

app/models/menu_item.rb
class MenuItem < ActiveRecord::Base
	belongs_to :meal
	has_many :ingredients
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def index
		@ingredients = Ingredient.all
		@user = User.find(1)
	end

	def new
		@ingredient = Ingredient.new
		session[:return_to] ||= request.referer
	end

	def edit
		@ingredient = Ingredient.find(params[:id])
		session[:return_to] ||= request.referer
	end

	def show
		@ingredient = Ingredient.find(params[:id])
		@user = User.find(1)
	end

	def destroy
		@ingredient = Ingredient.find(params[:id])
		@ingredient.destroy

		redirect_to request.referrer
	end

	def update
		@ingredient = Ingredient.find(params[:id]) 
		if @ingredient.update(ingredient_params)
			redirect_to session.delete(:return_to)
		else
			render 'edit'
		end
	end

	def create
		# binding.pry
		# pull in the data/params from the submitted form
		@ingredient = Ingredient.new(ingredient_params)
		@ingredient.menu_item = MenuItem.find(1)
		if @ingredient.save
			redirect_to session.delete(:return_to)
		else
			render "new"
		end
	end

	private
		def ingredient_params
			# allows submitted params to be mass assigned
			params.require(:ingredient).permit(:name)
		end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
	def show
		@meals = Meal.find(params[:id])
		@menuItem = MenuItem.where(meal_id:params[:id])
	end

	def new
		@meal = Meal.new
		session[:return_to] ||= request.referer
	end

	def edit
		@meal = Meal.find(params[:id])
		session[:return_to] ||= request.referer
	end

	def destroy
		@meal = Meal.find(params[:id])
		@meal.destroy

		redirect_to request.referrer
	end

	def update
		@meal = Meal.find(params[:id]) 
		if @meal.update(meal_params)
			redirect_to session.delete(:return_to)
		else
			render 'edit'
		end
	end

	def create
		# binding.pry
		# pull in the data/params from the submitted form
		@meal = Meal.new(meal_params)
		@meal.user = User.find(1)
		if @meal.save
			redirect_to session.delete(:return_to)
		else
			render "new"
		end
	end

	private
		def meal_params
			# allows submitted params to be mass assigned
			params.require(:meal).permit(:name)
		end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
	def index
		@menu_item = MenuItem.all
		@user = User.find(1)
	end

	def new
		@menu_item = MenuItem.new
		session[:return_to] ||= request.referer
	end

	def edit
		@menu_item = MenuItem.find(params[:id])
		session[:return_to] ||= request.referer
	end

	def show
		@menu_item = MenuItem.find(params[:id])
		@user = User.find(1)
		@ingredient = Ingredient.where(menu_item_id:params[:id])
	end

	def destroy
		@menu_item = MenuItem.find(params[:id])
		@menu_item.destroy

		redirect_to request.referrer
	end

	def update
		@menu_item = MenuItem.find(params[:id]) 
		if @menu_item.update(menu_item_params)
			redirect_to session.delete(:return_to)
		else
			render 'edit'
		end
	end

	def create
		# binding.pry
		# pull in the data/params from the submitted form
		@menu_item = MenuItem.new(menu_item_params)
		@menu_item.meal = Meal.find(1)
		if @menu_item.save
			redirect_to session.delete(:return_to)
		else
			render "new"
		end
	end

	private
		def menu_item_params
			# allows submitted params to be mass assigned
			params.require(:menu_item).permit(:name)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end

	def show
		@user = User.find(params[:id])
		@meals = Meal.where(user_id:params[:id])
	end


	# private

	# 	def recipe_params
	# 		params.require(:recipe).permit(:name, :summary, :description, :picture)
	# 	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_edit.html.erb
<div class="modal-wrap">
	<h3>Edit Ingredient</h3>
	<%= form_for @ingredient do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/ingredients/_new.html.erb
<div class="modal-wrap">
	<h3>New Ingredient</h3>
	<%= form_for @ingredient do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/ingredients/edit.js.erb
m = $('#modal');
m.html("<%= j render "edit"%>");
m.modal('show');

app/views/ingredients/new.js.erb
m = $('#modal');
m.html("<%= j render "new"%>");
m.modal('show');

app/views/layouts/_footer.html.erb
	<footer class="fluid-container">
		<div class="container">
			<p>&copy; 2015 | Danny Avery - Ruby On Rails :: Emergent Technology</p>
		</div>

		<div class="modal fade" id="modal" tabindex="-1" role="dialog">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        <h4 class="modal-title">Modal title</h4>
		      </div>
		      <div class="modal-body">
		        <p>One fine body&hellip;</p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-primary">Save changes</button>
		      </div>
		    </div><!-- /.modal-content -->
		  </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

	</footer>

</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FALLERGY</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<header class="navbar navbar-fixed-top navbar-default">
		<div class="container">
			<%= link_to "FAllergy App", root_path, class: "", id: "logo" %>
			<div class="get-app">
				<div class="get-app__ios"><a href="#"><%= image_tag("ios-app-store.png") %></a></div>
				<div class="get-app__google-play"><a href="#"><%= image_tag("google-play.png") %></a></div>
			</div>
			<!-- <div class="nav_item">
				<%= link_to "Recipes", '', class: "btn btn-default btn-warning" %>
			</div>
			<div class="nav_item">
				<%= link_to "Link 1", "", class: "btn btn-default btn-warning" %>
			</div>
			<div class="nav_item">
				<%= link_to "New Recipe", '', class: "btn btn-default btn-warning" %>
			</div> -->
		</div>
	</header>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>">
				<%= message %>
				<a href="" class="close" data-dismiss="alert">&#215;</a>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>

<div class="content">
		<%= render 'layouts/messages' %>
		<%= yield %>
</div>

<%= render 'layouts/footer' %>

app/views/meals/_edit.html.erb
<div class="modal-wrap">
	<h3>Edit Meal</h3>
	<%= form_for @meal do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/meals/_new.html.erb
<div class="modal-wrap">
	<h3>New Meal</h3>
	<%= form_for @meal do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/meals/edit.js.erb
m = $('#modal');
m.html("<%= j render "edit"%>");
m.modal('show');

app/views/meals/new.js.erb
m = $('#modal');
m.html("<%= j render "new"%>");
m.modal('show');

app/views/meals/show.html.erb
<div class="container">
	<div class="row">
		<h1><%= @meals.user.first_name %>'s Meal</h1>
		<%= link_to 'Back to Meal List', user_path(1), class: "btn btn-primary" %>
	</div>

	<div class="row">
		<hr>
		<div class="col-sm-4 time-meal">
			<h4><%= @meals.created_at.strftime("%-m/%-d/%y") %> @ <%= @meals.created_at.strftime("%H:%M") %></h4>
			<h3><%= @meals.name %></h3>
		</div>
		<div class="col-sm-8 menu-items">
			<h4 class="menu-items__header">Menu Item(s)</h4>
			<%= link_to "+ Add", new_menu_item_path, class: "btn btn-primary menu-items__add-link", remote: true %>
			<hr>
			<% @menuItem.each do |mi| %>
				<div class="col-xs-9 menu-item">
					<p class="text-align__left"><%= link_to "#{mi.name}", menu_item_path(mi) %></p>
				</div>
				<div class="col-xs-3 menu-item__action">
				<ul>
					<li>
						<%= link_to "", edit_menu_item_path(mi), class: "glyphicon glyphicon-edit", remote: true %>
					</li>
					<li class="text-align__right">
						<%= link_to "", menu_item_path(mi), class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: "Are you sure?" } %>
					</li>
				</ul>
				</div>
			<% end %>
		</div>
	</div>
</div><!-- container -->

app/views/menu_items/_edit.html.erb
<div class="modal-wrap">
	<h3>Edit Menu Item</h3>
	<%= form_for @menu_item do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
		<!-- (@menu_item.new_record? ? "New Menu Item" :  "Edit Menu Item") -->
	<% end %>
</div>

app/views/menu_items/_new.html.erb
<div class="modal-wrap">
	<h3>New Menu Item</h3>
	<%= form_for @menu_item do |f| %>
		<p>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</p>

		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/menu_items/edit.js.erb
m = $('#modal');
m.html("<%= j render "edit"%>");
m.modal('show');

app/views/menu_items/index.html.erb
<div class="container">
	<div class="row">
		<!-- <h1><%= @user.first_name %>'s Meal</h1> -->
		<h1><%= @menu_item.name %></h1>
		<%= link_to 'Back to Meal List', user_path(1), class: "btn btn-primary" %>
	</div>

	
</div><!-- container -->

app/views/menu_items/new.js.erb
m = $('#modal');
m.html("<%= j render "new"%>");
m.modal('show');

app/views/menu_items/show.html.erb
<div class="container">
	<div class="row">
		<h1><%= @user.first_name %>'s Meal</h1>
		<%= link_to 'Back to Menu Items', {:controller=>"meals", action: "show", :id => @menu_item.meal[:id] }, class: "btn btn-primary" %>
		<hr>

		<div class="col-sm-4 time-meal">
			<h3>Meal:</h3>
			<p><%= @menu_item.meal.name %></p>
			<p>Added: <%= @menu_item.meal.created_at.strftime("%-m/%-d/%y") %> @ <%= @menu_item.meal.created_at.strftime("%H:%M") %></p>
			<h3>Menu Item:</h3>
			<p><%= @menu_item.name %></p>
			<p>Added: <%= @menu_item.created_at.strftime("%-m/%-d/%y") %> @ <%= @menu_item.created_at.strftime("%H:%M") %></p>
		</div>

	<div class="col-sm-8 menu-items">
		<h4 class="menu-items__header">Ingredient(s)</h4>
		<%= link_to "+ Add", new_ingredient_path, class: "btn btn-primary menu-items__add-link", remote: true %>
		<hr>
		<% @ingredient.each do |mi| %>
			<div class="col-xs-9 menu-item">
				<p class="text-align__left"><%= link_to "#{mi.name}", ingredient_path(mi) %></p>
			</div>
			<div class="col-xs-3 menu-item__action">
			<ul>
				<li>
					<%= link_to "", edit_ingredient_path(mi), class: "glyphicon glyphicon-edit", remote: true %>
				</li>
				<li class="text-align__right">
					<%= link_to "", ingredient_path(mi), class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: "Are you sure?" } %>
				</li>
			</ul>
			</div>
		<% end %>
	</div>
	
	</div>
	
</div><!-- container -->

app/views/pages/home.html.erb
<div class="text-align__center jumbotron">
	<h1>Welcome to the <br> Fallergy App</h1>

	<p>An app that tracks the food you eat and the reactions to that food</p>

	<%= link_to "Try It Now", users_path, class: "btn btn-lg btn-primary" %>

</div>

<div class="container home-info-box">
	<div class="row">
		<div class="col-md-4">
			<h3 class="midrow">Common Food Allergies</h3>
			<p class="text-align__center home-info-box__description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae officia architecto quidem in error quia.</p>
			<p><%= link_to "Browse", "", class: "btn btn-small btn-warning" %></p>
		</div>
		<div class="col-md-4">
			<h3 class="midrow">Food Allergy Diets</h3>
			<p class="text-align__center home-info-box__description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae officia architecto quidem in error quia.</p>
			<p><%= link_to "Browse", "", class: "btn btn-small btn-warning" %></p>
		</div>
		<div class="col-md-4">
			<h3 class="midrow">Local Holistic Care</h3>
			<p class="text-align__center home-info-box__description">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae officia architecto quidem in error quia.</p>
			<p><%= link_to "Browse", "", class: "btn btn-small btn-warning" %></p>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
<h1>Account Info</h1>
<%= link_to 'Home', "/", class: "btn btn-primary" %>
<h3>User(s)</h3>
<hr>
<% @user.each do |u| %>
	<div class="user">
		<ul>
			<li><h4><%= link_to "#{u.first_name} #{u.last_name}", user_path(u) %></h4></li>
			<li><%= u.email %></li>
		</ul>
	</div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="meals container">
<h1><%= link_to "#{@user.first_name} #{@user.last_name}", user_path(1) %></h1>
<%= link_to 'Back to Users', users_path, class: "btn btn-primary" %>
<div style="clear: both;"></div>
<h3 style="float: left;">Meal(s)</h3>
<div style="float: right; display: inline-block; margin-top: 20px;"><%= link_to "+ Add", new_meal_path, class: "btn btn-primary", remote: true %></div>
<div style="clear: both;"></div>
	<% @meals.each do |m| %>
		<hr style="clear: both;">
		<ul>
			<li>
				<h4>
					<%= link_to "#{m.name}", meal_path(m.id) %>

					<span style="display: inline-block; margin-left: 20px;"></span> 

					<%= link_to "", edit_meal_path, class: "glyphicon glyphicon-edit", remote: true %> 
					<span style="display: inline-block;"></span> 
					
					<%= link_to "", meal_path(m), class: "glyphicon glyphicon-remove", method: :delete, data: { confirm: "Are you sure?" } %>
				</h4>

				<p><span class="quiet"><small><%= time_ago_in_words(m.created_at) %> ago</small></span></p>
			</li>
		</ul>
	<% end %>
</div>